### ISSUE TITLE
Change the theme color of site to red

### ISSUE THREAD

**Issue by magictwicks** [mikeryu/westmont-cs130-f23-team-maroon#48]
Make the default Bulma primary color to be the standard Westmont maroon. probably will need to modify Sass variables and set the primary color to: #D21D50 or #9C1B3F

**Comment by alpetee** [comment]
![Image](https://github.com/mikeryu/westmont-cs130-f23-team-maroon/assets/143764997/0fb34646-57ca-4f18-b690-4917f480a0ab)

all blue's into red
