### ISSUE TITLE
Show list of all persons who have RSVP'd on the Event Detail page

### ISSUE THREAD

**Issue by magictwicks** [mikeryu/westmont-cs130-f23-team-maroon#49]
Display a list of all people who have signed up for an event on the event detail page seen below.  

![Image](https://user-images.githubusercontent.com/49892992/277821986-3a857bac-deea-421a-9f9b-8c35bc7d8cd0.png)

**Comment by alpetee** [comment]
blocked bc other rsvp tickets need to be completed first
