### ISSUE TITLE
Display tasks assigned to an event on eventDetails page

### ISSUE THREAD

**Issue by magictwicks** [mikeryu/westmont-cs130-f23-team-maroon#55]
The user should be able to open the event details page and see all of the tasks that relate to the event. The tasks should be seen under the description area (see wireframe) as a text list.

This could be implemented by passing in all Task objects with the given event as the foreign key into the context of the eventDetail view. 

![Image](https://github.com/mikeryu/westmont-cs130-f23-team-maroon/assets/85504364/49712f18-058a-4590-9a8f-61a9b85a22d5)

**Comment by alpetee** [comment]
only allows a certian word count of text to be displayed for each task-- a "..." after 150?

**Comment by jnielsen713** [comment]
I'd say so, at least only if there's a way to expand it so you can see the whole thing.

**Comment by alpetee** [comment]
@jnielsen713 After some thinking I think it makes sense to limit the user from typing in tasks that are sillily long. Im implementing that on this ticket as well, but it shouldn't be hard to fix if you think we should do something else.
