### ISSUE TITLE
Update the RSVP model to include task sign ups and the RSVP view (backend)

### ISSUE THREAD

**Issue by magictwicks** [mikeryu/westmont-cs130-f23-team-maroon#56]
The RSVP model should be able to be connected to a task (using ForeignKey) for a given event. This way when the functionality to RSVP for a task is added the system will be able to store which Task the person who created the RSVP wishes to sign up for. 

Additionally, the event detail view needs to be updated to handle the new RSVP form when the user RSVPs with a task. The new RSVP from will look like something below

![Image](https://github.com/mikeryu/westmont-cs130-f23-team-maroon/assets/85504364/a423679a-e68d-4a82-993d-4671838996c4)

**Comment by alpetee** [comment]
Also displays who has signed up for the task
