### ISSUE TITLE
Handle errors with too many chars typed into text feilds for creating events (backend)

### ISSUE THREAD

**Issue by alpetee** [mikeryu/westmont-cs130-f23-team-maroon#58]
Prevents the user from continuing typing in characters when a certain limit is reached in the create events form. The limits are given below with the following specifications:

For the title: 250 characters max
For the description: 1000 characters max
For everything else: 100 characters max; 

Should be easily implemented with HTML or javascript

**Comment by jnielsen713** [comment]
Alternatively, we could figure out how to have the text box stop allowing input after a certain number of characters are typed. The original option gives the users room to complete their thought, but this method would prevent unnecessary work being done by the user
