### ISSUE TITLE
Sign Up and Login backend functionality

### ISSUE THREAD

**Issue by IsaaMaster** [mikeryu/westmont-cs130-f23-team-maroon#61]
Set up backend functionality for login and sign-up logic. Eventually, the user should be able to sign up with a username and password, and then log in with that same username and password. 

For this several things will need to be done:
1. the default redirect after login and logout needs to set up in settings.py
2. views for login and sign-up need to be designed to authenticate the user or create a new user. 

Note to QAE: Things to test - 
1. The user can sign up on the signup page log out and then log back in with the same account. 
2. The user cannot access the Event Details page, the Browse Events page, and the Create Event page while logged out and should be redirected to the login page if they try to do so. 
3. The user cannot access the login page, the signup page, and the welcome page if they are signed in, and should be redirected to the browse events page if they try to do so. 
4. The signup page, login page, and welcome page should have the login and sign-up buttons in their navbar, and the other three pages should have the signup buttons. 

![Image](https://github.com/mikeryu/westmont-cs130-f23-team-maroon/assets/85504364/308146a9-d6a4-45b8-b272-e566d53388f4)

**Comment by jnielsen713** [comment]
Does this include creating the sign up and login pages? I'm happy to work on those if needed

**Comment by HTQun** [comment]
Hi, can you assigned for me?
